# name of workflow
name: CI


# event to trigger the workflow
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
      
# jobs to run after event is triggered
# job1
jobs:
  build:
      # operating system to use
      runs-on: ubuntu-latest
      
      steps:
      
      # step1: checkout repository under $GITHUB_WORKSPACE, so our workflow can access it
        -
          name: Checkout
          uses: actions/checkout@v2
      
      # step2: login to docker hub using our github secrets for username and personal access token
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with: 
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # step3: setup Docker Buildx to create the buider instance using a BuildKit container under the hood
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
      # step4: build and push changes to dockerhub   
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/neuronal_promoters:latest
            cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/neuronal_promoters:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/neuronal_promoters:buildcache,mode=max
